version: '3.8'

services:
  app:
    container_name: next-demo-app
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: sh -c "yarn install && yarn run dev"
    environment:
      - PORT=4001
    env_file:
      - .env

volumes:
  next-demo-app: